"""Add created_at to expenses

Revision ID: 08b07f1e9594
Revises: 9aecbde66fbc
Create Date: 2026-07-25 11:53:46.256809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b07f1e9594'
down_revision: Union[str, Sequence[str], None] = '9aecbde66fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. Add created_at temporarily allowing NULL
    op.add_column(
        'expenses',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )

    # 2. Give existing expenses the current timestamp
    op.execute(
        "UPDATE expenses SET created_at = NOW() WHERE created_at IS NULL"
    )

    # 3. Make created_at required
    op.alter_column(
        'expenses',
        'created_at',
        nullable=False
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'created_at')
    # ### end Alembic commands ###
